1. Write a Python Program to Add Two Matrices?

In [1]:
def add_matrices(matrix1, matrix2):
    if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
        return "Matrices should have the same dimensions"

    result = [[0 for _ in range(len(matrix1[0]))] for _ in range(len(matrix1))]

    # Iterate over the elements of the matrices and add them
    for i in range(len(matrix1)):
        for j in range(len(matrix1[0])):
            result[i][j] = matrix1[i][j] + matrix2[i][j]

    return result


matrix1 = [[9, 0, 3], [4, 5, 6], [4, 8, 9]]
matrix2 = [[9, 8, 7], [8, 7, 4], [7, 2, 1]]

result = add_matrices(matrix1, matrix2)
if isinstance(result, str):
    print(result)
else:
    for row in result:
        print(row)


[18, 8, 10]
[12, 12, 10]
[11, 10, 10]


2. Write a Python Program to Multiply Two Matrices?

In [4]:
import numpy as np

matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])

result = np.dot(matrix1, matrix2)
print(result)


[[ 58  64]
 [139 154]]


3. Write a Python Program to Transpose a Matrix?

In [5]:
import numpy as np
matrix = np.array([[9, 2, 3], [7, 7, 6], [3, 0, 9]])

transposed_matrix = np.transpose(matrix)

print("Original Matrix:")
print(matrix)

print("\nTransposed Matrix:")
print(transposed_matrix)


Original Matrix:
[[9 2 3]
 [7 7 6]
 [3 0 9]]

Transposed Matrix:
[[9 7 3]
 [2 7 0]
 [3 6 9]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [7]:
def sort_words_alphabetically(words):
    sorted_words = sorted(words)
    return sorted_words

word_list = ["me", "banana", "larry", "date", "fig"]
sorted_words = sort_words_alphabetically(word_list)

print("Sorted words:")
for word in sorted_words:
    print(word)


Sorted words:
banana
date
fig
larry
me


5. Write a Python Program to Remove Punctuation From a String?

In [14]:
word = "debnandini.dey"
word_without_dot = word.replace(".", "")
print(word_without_dot)


debnandinidey
